version: "3"

services:
  database:
    image: postgres:14.1-alpine
    container_name: evrika_postgres_dev
    env_file:
      - dev.env
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - evrika_data:/var/lib/postgresql/data

    networks:
      - evrika_net_dev

  backend:
    build:
      context: .
      dockerfile: ./docker/dev/BackendDockerfile
    container_name: evrika_django_dev
    command: python manage.py runserver 0.0.0.0:8000 --settings=config.settings.server
    env_file:
      - dev.env
    volumes:
      - ./backend/:/app
    depends_on:
      - database
    ports:
      - "8000:8000"
    tty: true
    networks:
      - evrika_net_dev

  frontend:
    build:
      context: .
      dockerfile: ./docker/dev/FrontendDockerfile
    container_name: evrika_vuejs_dev
    command: ./docker/dev/frontend_setup.sh
    volumes:
      - .:/app
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - evrika_net_dev

volumes:
  evrika_data:
    driver: local

networks:
  evrika_net_dev:
