version: '3'

services:
  postgres:
    container_name: evrika_postgres_dev
    image: postgres:14.1-alpine
    env_file:
      - dev.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evrika_net_dev

networks:
  evrika_net_dev:

volumes:
  postgres_data:
    driver: local
