# Generated by Django 4.1.5 on 2023-04-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evrika', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Patronymic'),
        ),
    ]
