# Generated by Django 4.1.5 on 2023-04-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evrika', '0002_alter_user_patronymic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='impletementer',
            new_name='implementer',
        ),
    ]
