# Generated by Django 4.1.5 on 2023-05-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evrika', '0003_rename_impletementer_project_implementer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='users_view',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Project views'),
        ),
    ]
