# Generated by Django 3.2.15 on 2022-09-04 08:54

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('evrika', '0005_direction_project_projectfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evrika.project', verbose_name='Project id')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evrika.student', verbose_name='Student id')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
